/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package product.view;

import provider.view.*;
import shared.view.SwitchJPanel;
import java.util.Map;
import javax.swing.JOptionPane;
import product.controller.AdminProduct;
import provider.controller.AdminProvider;

/**
 *
 * @author Izanami
 */
public class ViewModifyProductPanel extends SwitchJPanel {

    /**
     * Creates new form ViewModifyProviderPanel
     */
    public ViewModifyProductPanel() {
        initComponents();
        this.adminProduct = null;
    }
    public ViewModifyProductPanel(AdminProduct adminProduct) {
        initComponents();
        this.adminProduct = adminProduct;
    }
    
    @Override
    public void setData(String barcode) {
        dataProduct = adminProduct.getDataProduct(barcode);

        barcodeTextField.setText(dataProduct.get("barcode"));
        descriptionTextField.setText(dataProduct.get("description"));
        priceUnitTextField.setText(dataProduct.get("priceUnit"));
        saleUnitTextField.setText(dataProduct.get("priceSaleUnit"));
        departamentTextField.setText(dataProduct.get("departament"));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionProductLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        barcodeLabel = new javax.swing.JLabel();
        barcodeTextField = new javax.swing.JTextField();
        departamentLabel = new javax.swing.JLabel();
        departamentTextField = new javax.swing.JTextField();
        modifyProductButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        moduleNameLabel = new javax.swing.JLabel();
        saleUnitLabel = new javax.swing.JLabel();
        priceUnitLabel = new javax.swing.JLabel();
        saleUnitTextField = new javax.swing.JTextField();
        priceUnitTextField = new javax.swing.JTextField();
        currentStockLabel = new javax.swing.JLabel();
        currentStockTextField = new javax.swing.JTextField();
        minimunStockLabel = new javax.swing.JLabel();
        minimunStockTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Modificar proveedor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 0));
        titleLabel.setText("MODIFICAR PRODUCTO");

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(204, 204, 0));
        descriptionLabel.setText("- Modifique la siguiente informacion acerca del nuevo producto:");

        descriptionProductLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptionProductLabel.setText("Descripción");

        descriptionTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptionTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        descriptionTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        descriptionTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        barcodeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barcodeLabel.setText("Código de barras");

        barcodeTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        barcodeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        barcodeTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        barcodeTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        departamentLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        departamentLabel.setText("Departamento");

        departamentTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        departamentTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        departamentTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        departamentTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        modifyProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modifyProductButton.setText("Guardar cambios");
        modifyProductButton.setPreferredSize(new java.awt.Dimension(150, 30));
        modifyProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProvider(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(153, 0, 0));
        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelModifyProvider(evt);
            }
        });

        moduleNameLabel.setBackground(new java.awt.Color(204, 204, 0));
        moduleNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moduleNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        moduleNameLabel.setText("    PRODUCTOS");
        moduleNameLabel.setOpaque(true);
        moduleNameLabel.setPreferredSize(new java.awt.Dimension(600, 30));

        saleUnitLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        saleUnitLabel.setText("Unidad de venta");

        priceUnitLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        priceUnitLabel.setText("Precio de unidad");

        saleUnitTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        saleUnitTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        saleUnitTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        saleUnitTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        priceUnitTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        priceUnitTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        priceUnitTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        priceUnitTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        currentStockLabel.setText("Cantidad actual");

        currentStockTextField.setText("0");
        currentStockTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        currentStockTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        minimunStockLabel.setText("Cantidad actual");

        minimunStockTextField.setText("0");
        minimunStockTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        minimunStockTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(titleLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(descriptionProductLabel)
                                .addComponent(barcodeLabel)
                                .addComponent(priceUnitLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(modifyProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(currentStockLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(currentStockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(minimunStockLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minimunStockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(saleUnitLabel)
                                        .addComponent(departamentLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(saleUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(departamentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(150, 150, 150))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcodeLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionProductLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleUnitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentStockLabel)
                    .addComponent(currentStockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimunStockLabel)
                    .addComponent(minimunStockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProvider
        String description = descriptionTextField.getText();
        long barcode = Long.valueOf(barcodeTextField.getText());
        String departament = departamentTextField.getText();
        String saleUnit = saleUnitTextField.getText();
        double prieUnit = Double.valueOf(priceUnitTextField.getText());
        
        adminProduct.modifyProduct(barcode, description, prieUnit, saleUnit, departament);
        
        String message = "Se ha modificado el producto con el código de " +
            "barras: " + barcode + ".";
        JOptionPane.showMessageDialog(null, message);
        
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_modifyProvider

    private void cancelModifyProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelModifyProvider
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_cancelModifyProvider


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JTextField barcodeTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentStockLabel;
    private javax.swing.JTextField currentStockTextField;
    private javax.swing.JLabel departamentLabel;
    private javax.swing.JTextField departamentTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionProductLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel minimunStockLabel;
    private javax.swing.JTextField minimunStockTextField;
    private javax.swing.JButton modifyProductButton;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JLabel priceUnitLabel;
    private javax.swing.JTextField priceUnitTextField;
    private javax.swing.JLabel saleUnitLabel;
    private javax.swing.JTextField saleUnitTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    private AdminProduct adminProduct;
    private Map<String,String> dataProduct;
}
