/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.services;

import view.SwitchJPanel;
import java.util.Map;
import controller.AdminService;
import static data.ServiceConstants.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Izanami
 */
public class ViewModifyServicePanel extends SwitchJPanel {

    /**
     * Creates new form ViewModifyProviderPanel
     */
    public ViewModifyServicePanel() {
        initComponents();
        this.adminService = null;
    }
    public ViewModifyServicePanel(AdminService adminService) {
        initComponents();
        this.adminService=adminService;
    }
    
    @Override
    public void setData(String identifier) {
        dataService = adminService.getDataService(identifier);
        descriptionTextField.setText(dataService.get(DESCRIPTION));
        characteristicsTextField.setText(dataService.get(CHARACTERISTICS));
        estimatePriceTextField.setText(dataService.get(ESTIMATE_PRICE));
        dateReceiptTextField.setText(dataService.get(DATE_RECEIPT));
        dateDeliveryTextField.setText(dataService.get(DATE_DELIVERY));
        if (dataService.get(IS_DID).equals("true")) isDid.setSelected(true);
        if (dataService.get(IS_DID).equals("false")) isNotDid.setSelected(true);
        if (dataService.get(IS_DELIVERED).equals("true")) deliveried.setSelected(true);
        if (dataService.get(IS_DELIVERED).equals("false")) notDeliveried.setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isDidGroup = new javax.swing.ButtonGroup();
        isDeliveriedGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        characteristicsTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        estimatePriceTextField = new javax.swing.JTextField();
        modifyServiceButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        moduleNameLabel = new javax.swing.JLabel();
        phoneLabel1 = new javax.swing.JLabel();
        phoneLabel2 = new javax.swing.JLabel();
        dateReceiptTextField = new javax.swing.JTextField();
        dateDeliveryTextField = new javax.swing.JTextField();
        isDidLabel3 = new javax.swing.JLabel();
        isDeliveriedLabel = new javax.swing.JLabel();
        isDid = new javax.swing.JRadioButton();
        isNotDid = new javax.swing.JRadioButton();
        deliveried = new javax.swing.JRadioButton();
        notDeliveried = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("Modificar proveedor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(51, 51, 255));
        titleLabel.setText("MODIFICAR SERVICIO");

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 51, 255));
        descriptionLabel.setText("- Modifique la siguiente informacion acerca del servicio:");

        nameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameLabel.setText("Descripcion");

        descriptionTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptionTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        descriptionTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        descriptionTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        addressLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addressLabel.setText("Caracteristicas");

        characteristicsTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        characteristicsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        characteristicsTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        characteristicsTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        phoneLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel.setText("Precio estimado");

        estimatePriceTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estimatePriceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        estimatePriceTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        estimatePriceTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        modifyServiceButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modifyServiceButton.setText("Guardar cambios");
        modifyServiceButton.setPreferredSize(new java.awt.Dimension(150, 30));
        modifyServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyService(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(153, 0, 0));
        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelModifyProvider(evt);
            }
        });

        moduleNameLabel.setBackground(new java.awt.Color(51, 51, 255));
        moduleNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moduleNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        moduleNameLabel.setText("    SERVICIOS");
        moduleNameLabel.setOpaque(true);
        moduleNameLabel.setPreferredSize(new java.awt.Dimension(600, 30));

        phoneLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel1.setText("Fecha de recibo");

        phoneLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel2.setText("Fecha de entrega");

        dateReceiptTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dateReceiptTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        dateReceiptTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        dateReceiptTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        dateDeliveryTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dateDeliveryTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        dateDeliveryTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        dateDeliveryTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        isDidLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isDidLabel3.setText("Terminado");

        isDeliveriedLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        isDeliveriedLabel.setText("Entregado");

        isDid.setBackground(new java.awt.Color(255, 255, 255));
        isDidGroup.add(isDid);
        isDid.setText("Terminado");

        isNotDid.setBackground(new java.awt.Color(255, 255, 255));
        isDidGroup.add(isNotDid);
        isNotDid.setText("No terminado");

        deliveried.setBackground(new java.awt.Color(255, 255, 255));
        isDeliveriedGroup.add(deliveried);
        deliveried.setText("Entreagado");

        notDeliveried.setBackground(new java.awt.Color(255, 255, 255));
        isDeliveriedGroup.add(notDeliveried);
        notDeliveried.setText("No entregaado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(addressLabel)
                            .addComponent(phoneLabel)
                            .addComponent(phoneLabel1)
                            .addComponent(phoneLabel2)
                            .addComponent(isDidLabel3)
                            .addComponent(isDeliveriedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(estimatePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(characteristicsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(dateReceiptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateDeliveryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(isDid)
                                    .addGap(27, 27, 27)
                                    .addComponent(isNotDid)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deliveried)
                                .addGap(18, 18, 18)
                                .addComponent(notDeliveried))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modifyServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characteristicsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel1)
                    .addComponent(dateReceiptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel2)
                    .addComponent(dateDeliveryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isDid)
                    .addComponent(isNotDid)
                    .addComponent(isDidLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveried)
                    .addComponent(notDeliveried)
                    .addComponent(isDeliveriedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyService(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyService
        String identifier = dataService.get(IDENTIFIER);
        String description = descriptionTextField.getText();
        String characteristics = characteristicsTextField.getText();
        String estimatePrice = estimatePriceTextField.getText();
        String dateReceipt = dateReceiptTextField.getText();
        String dateDelivery = dateDeliveryTextField.getText();
        boolean isDid = false;
        if (this.isDid.isSelected()) {
            isDid = true;
        }
        boolean isDeliveried = false;
        if (deliveried.isSelected()) {
            isDeliveried = true;
        }

        adminService.modifyService(identifier, description, characteristics, 
                estimatePrice, dateReceipt, dateDelivery, isDid, isDeliveried);
        
        String message = "Se ha modificado el servicio numero "+identifier+".";
        JOptionPane.showMessageDialog(null, message);
        
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_modifyService

    private void cancelModifyProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelModifyProvider
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_cancelModifyProvider


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField characteristicsTextField;
    private javax.swing.JTextField dateDeliveryTextField;
    private javax.swing.JTextField dateReceiptTextField;
    private javax.swing.JRadioButton deliveried;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField estimatePriceTextField;
    private javax.swing.ButtonGroup isDeliveriedGroup;
    private javax.swing.JLabel isDeliveriedLabel;
    private javax.swing.JRadioButton isDid;
    private javax.swing.ButtonGroup isDidGroup;
    private javax.swing.JLabel isDidLabel3;
    private javax.swing.JRadioButton isNotDid;
    private javax.swing.JButton modifyServiceButton;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton notDeliveried;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    private AdminService adminService;
    private Map<String,String> dataService;
}
