/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.services;

import view.SwitchJPanel;
import java.util.Map;
import controller.AdminService;
import static data.ServiceConstants.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Izanami
 */
public class ViewRemoveServicePanel extends SwitchJPanel {

    /**
     * Creates new form ViewRemoveProviderPanel
     */
    public ViewRemoveServicePanel() {
        initComponents();
        this.adminService = null;
        this.dataService = null;
    }

    public ViewRemoveServicePanel(AdminService adminService) {
        initComponents();
        this.adminService = adminService;
        this.dataService = null;
    }
    
    @Override
    public void setData(String identifier) {
        dataService = adminService.getDataService(identifier);
        descriptionTextField.setText(dataService.get(DESCRIPTION));
        characteristicsTextField.setText(dataService.get(CHARACTERISTICS));
        estimatePrice.setText(dataService.get(ESTIMATE_PRICE));
        dateReceipt.setText(dataService.get(DATE_RECEIPT));
        dateDelivery.setText(dataService.get(DATE_DELIVERY));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        removeProviderButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        descriptionTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        characteristicsTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneLabel1 = new javax.swing.JLabel();
        phoneLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        estimatePrice = new javax.swing.JTextField();
        dateReceipt = new javax.swing.JTextField();
        dateDelivery = new javax.swing.JTextField();
        moduleNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 500));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 255));
        titleLabel.setText("ELIMINAR SERVICIO");

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 0, 255));
        descriptionLabel.setText("- Verifique que sea el servicio que quiere eliminar.");

        removeProviderButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeProviderButton.setText("Elminar Servicio");
        removeProviderButton.setPreferredSize(new java.awt.Dimension(150, 30));
        removeProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProvider(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(153, 0, 0));
        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRemoveProvider(evt);
            }
        });

        descriptionTextField.setBackground(new java.awt.Color(204, 204, 255));
        descriptionTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptionTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        descriptionTextField.setEnabled(false);
        descriptionTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        descriptionTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        addressLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addressLabel.setText("Caracteristicas");

        characteristicsTextField.setBackground(new java.awt.Color(204, 204, 255));
        characteristicsTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        characteristicsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        characteristicsTextField.setEnabled(false);
        characteristicsTextField.setMinimumSize(new java.awt.Dimension(10, 20));
        characteristicsTextField.setPreferredSize(new java.awt.Dimension(10, 20));

        phoneLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel.setText("Precio estimado");

        phoneLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel1.setText("Fecha de recibo");

        phoneLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        phoneLabel2.setText("Fecha de entrega");

        nameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameLabel.setText("Descripcion");

        estimatePrice.setBackground(new java.awt.Color(204, 204, 255));
        estimatePrice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estimatePrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        estimatePrice.setEnabled(false);
        estimatePrice.setMinimumSize(new java.awt.Dimension(10, 20));
        estimatePrice.setPreferredSize(new java.awt.Dimension(10, 20));

        dateReceipt.setBackground(new java.awt.Color(204, 204, 255));
        dateReceipt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dateReceipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        dateReceipt.setEnabled(false);
        dateReceipt.setMinimumSize(new java.awt.Dimension(10, 20));
        dateReceipt.setPreferredSize(new java.awt.Dimension(10, 20));

        dateDelivery.setBackground(new java.awt.Color(204, 204, 255));
        dateDelivery.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dateDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        dateDelivery.setEnabled(false);
        dateDelivery.setMinimumSize(new java.awt.Dimension(10, 20));
        dateDelivery.setPreferredSize(new java.awt.Dimension(10, 20));

        moduleNameLabel.setBackground(new java.awt.Color(51, 51, 255));
        moduleNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moduleNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        moduleNameLabel.setText("    SERVICIOS");
        moduleNameLabel.setOpaque(true);
        moduleNameLabel.setPreferredSize(new java.awt.Dimension(600, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addComponent(titleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLabel)
                                    .addComponent(addressLabel)
                                    .addComponent(phoneLabel)
                                    .addComponent(phoneLabel1)
                                    .addComponent(phoneLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(estimatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(characteristicsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(removeProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characteristicsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel1)
                    .addComponent(dateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel2)
                    .addComponent(dateDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProvider
        String identifierService = dataService.get(IDENTIFIER);
        adminService.removeService(identifierService);
        
        String message = "Se ha eliminado el servicio numero "+identifierService+".";
        JOptionPane.showMessageDialog(null, message);
        
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_removeProvider

    private void cancelRemoveProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRemoveProvider
        swapPanels();
        switchPanel.setData(null);
    }//GEN-LAST:event_cancelRemoveProvider


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField characteristicsTextField;
    private javax.swing.JTextField dateDelivery;
    private javax.swing.JTextField dateReceipt;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField estimatePrice;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JButton removeProviderButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    private AdminService adminService;
    private Map<String,String> dataService;
}
