/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package provider.view;

import shared.view.SwitchJPanel;
import provider.controller.AdminProvider;

/**
 *
 * @author Izanami
 */
public class ViewRemoveProviderTablePanel extends SwitchJPanel {

    /**
     * Creates new form ViewRemoveProviderTablePanel
     */
    public ViewRemoveProviderTablePanel() {
        initComponents();
        this.adminProvider = null;
    }

    public ViewRemoveProviderTablePanel(AdminProvider adminProvider) {
        initComponents();
        this.adminProvider = adminProvider;
    }
    
    @Override
    public void setData(String data) {
        String nameProvider = nameProviderTextField.getText();
        Object listProvider[][] = adminProvider.getProviderList(nameProvider);
        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            listProvider,
            new String [] {
                "Número", "Proveedor"
            }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        removeProviderTable = new javax.swing.JTable();
        nameProviderTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        removeProviderButton = new javax.swing.JButton();

        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Proveedor"
            }
        ));
        jScrollPane5.setViewportView(removeProviderTable);

        nameProviderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                updateTable(evt);
            }
        });

        jLabel15.setText("Teclee el nombre del proveedor:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Eliminar Proveedor");

        removeProviderButton.setText("Aceptar");
        removeProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProvider(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(nameProviderTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel15))
                        .addComponent(removeProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameProviderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeProviderButton)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProvider
        int selectedRow = removeProviderTable.getSelectedRow();
        Object identifier = removeProviderTable.getValueAt(selectedRow, 0);
        swapPanels();
        switchPanel.setData(identifier.toString());
    }//GEN-LAST:event_selectProvider

    private void updateTable(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTable
        String nameProvider = nameProviderTextField.getText();
        Object listProvider[][] = adminProvider.getProviderList(nameProvider);
        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            listProvider,
            new String [] {
                "Número", "Proveedor"
            }
        ));
    }//GEN-LAST:event_updateTable


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nameProviderTextField;
    private javax.swing.JButton removeProviderButton;
    private javax.swing.JTable removeProviderTable;
    // End of variables declaration//GEN-END:variables
    
    private AdminProvider adminProvider;
}
