/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package provider.view;

import shared.view.SwitchJPanel;
import provider.controller.AdminProvider;

/**
 *
 * @author Izanami
 */
public class ViewRemoveProviderTablePanel extends SwitchJPanel {

    /**
     * Creates new form ViewRemoveProviderTablePanel
     */
    public ViewRemoveProviderTablePanel() {
        initComponents();
        this.adminProvider = null;
    }

    public ViewRemoveProviderTablePanel(AdminProvider adminProvider) {
        initComponents();
        this.adminProvider = adminProvider;
    }
    
    @Override
    public void setData(String data) {
        String nameProvider = nameProviderTextField.getText();
        Object listProvider[][] = adminProvider.getProviderList(nameProvider);
        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            listProvider,
            new String [] {
                "Número", "Proveedor"
            }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        nameProviderTextField = new javax.swing.JTextField();
        removeProviderButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        removeProviderTable = new javax.swing.JTable();
        moduleNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(288, 312));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 0));
        titleLabel.setText("Eliminar Proveedor");

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(0, 102, 0));
        descriptionLabel.setText("Teclee el nombre del proveedor:");

        nameProviderTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameProviderTextField.setPreferredSize(new java.awt.Dimension(288, 25));
        nameProviderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                updateTable(evt);
            }
        });

        removeProviderButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeProviderButton.setText("Aceptar");
        removeProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProvider(evt);
            }
        });

        removeProviderTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Proveedor"
            }
        ));
        removeProviderTable.setMinimumSize(new java.awt.Dimension(30, 143));
        jScrollPane5.setViewportView(removeProviderTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeProviderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(descriptionLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(titleLabel))
                    .addComponent(nameProviderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameProviderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moduleNameLabel.setBackground(new java.awt.Color(0, 153, 51));
        moduleNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moduleNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        moduleNameLabel.setText("    PROVEEDORES");
        moduleNameLabel.setOpaque(true);
        moduleNameLabel.setPreferredSize(new java.awt.Dimension(600, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(moduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectProvider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProvider
        int selectedRow = removeProviderTable.getSelectedRow();
        Object identifier = removeProviderTable.getValueAt(selectedRow, 0);
        swapPanels();
        switchPanel.setData(identifier.toString());
    }//GEN-LAST:event_selectProvider

    private void updateTable(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateTable
        String nameProvider = nameProviderTextField.getText();
        Object listProvider[][] = adminProvider.getProviderList(nameProvider);
        removeProviderTable.setModel(new javax.swing.table.DefaultTableModel(
            listProvider,
            new String [] {
                "Número", "Proveedor"
            }
        ));
    }//GEN-LAST:event_updateTable


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JTextField nameProviderTextField;
    private javax.swing.JButton removeProviderButton;
    private javax.swing.JTable removeProviderTable;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    private AdminProvider adminProvider;
}
