
package view;

import javax.swing.JTabbedPane;

/**
 *
 * @author Izanami
 */
public abstract class SwitchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SwitchJPanel
     */
    public SwitchJPanel() {
        initComponents();
    }

    public void setTabs(JTabbedPane tabs){
        this.tabs = tabs;
    }
    
    public void setSwitchPanel(SwitchJPanel switchPanel){
        this.switchPanel = switchPanel;
    }
    
    public void swapPanels(){
        int indexTab = tabs.indexOfComponent(this);
        tabs.remove(indexTab);
        tabs.insertTab(switchPanel.getName(), null, switchPanel, null, indexTab);
        tabs.setSelectedIndex(indexTab);
    }
    
    public abstract void setData(String data);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private JTabbedPane tabs;
    protected SwitchJPanel switchPanel;
}
